name: UAV_24_test
channels:
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libnsl=2.0.1
  - libsqlite=3.46.1
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - python=3.9.20
  - readline=8.2
  - setuptools=75.1.0
  - tk=8.6.13
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - accelerate==0.18.0
      - antlr4-python3-runtime==4.9.3
      - av==9.1.0
      - bitsandbytes==0.44.0
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - cmake==3.30.3
      - coloredlogs==15.0.1
      - decord==0.6.0
      - diffusers==0.16.0
      - einops==0.8.0
      - ffmpeg==1.4
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fsspec==2024.9.0
      - huggingface-hub==0.25.1
      - humanfriendly==10.0
      - idna==3.10
      - imageio==2.25.0
      - imageio-ffmpeg==0.4.8
      - importlib-metadata==8.5.0
      - jinja2==3.1.4
      - lit==18.1.8
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.2.1
      - numpy==1.24.3
      - nvidia-cuda-nvrtc-cu12
      - nvidia-cuda-runtime-cu12
      - omegaconf==2.3.0
      - onnx==1.17.0
      - onnxruntime-gpu==1.19.2
      - onnxsim==0.4.36
      - opencv-python==4.10.0.84
      - packaging==24.1
      - pandas==2.2.3
      - pillow==10.4.0
      - protobuf==5.28.2
      - psutil==6.0.0
      - pyfiglet==1.0.2
      - pygments==2.18.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.1
      - rotary-embedding-torch==0.2.3
      - scipy==1.13.1
      - sentencepiece==0.1.99
      - six==1.16.0
      - sympy==1.13.3
      - timm==0.4.12
      - tokenizers==0.13.3
      - torch==2.4.1 --index-url https://download.pytorch.org/whl/cu124
      - torchao==0.5.0
      - torchaudio==2.4.1 --index-url https://download.pytorch.org/whl/cu124
      - torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cu124
      - tqdm==4.66.5
      - transformers==4.28.1
      - triton==3.0.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - xformers==0.0.28.post1
      - zipp==3.20.2
